### ISSUE TITLE
Cannot query tesseract on localhost

### ISSUE THREAD

**Issue by DerekMaggio** [ucd-library/csus-sp-2018-app#28]
@jrmerz I am trying to query tesseract on my local fin-example-repo I have running. My server is tied to port 3000. When I run this http://localhost:3000/fcrepo/rest/collection/sherry-lehmann/catalogs/d7q30n/media/images/d7q30n-002/svc:tesseract/2008,2543,220,80/full/0/default.jpg url I am getting an response saying I am unauthorized. I changed the call to http from https. Is this where I need to start setting up authentication to communicate with my localhost?

**Comment by DerekMaggio** [comment]
I have been trying to use digital.ucdavis.edu as an endpoint to query but I have stopped getting responses from it as of last friday.

**Comment by jrmerz** [comment]
1) You can't use https on localhost without a bit of work, so that is not your problem (and I don't recommend https locally, it's just a pain).

2) Does http://localhost:3000/fcrepo/rest/collection/sherry-lehmann/catalogs/d7q30n/media/images/d7q30n-002 exist?  You might get a unauthorized response to services if the fedora endpoint doesn't exist (this is a bug, should be 404). 

3) curl https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/catalogs/d7q30n/media/images/d7q30n-002/svc:tesseract/2008,2543,220,80/full/0/default.jpg seems to be hanging but accessing via the browser does work.... will investigate.  Thanks for the heads up.

**Comment by jrmerz** [comment]
```bash
curl https://digital.ucdavis.edu/fcrepo/rest/collection/sherry-lehmann/catalogs/d7q30n/media/images/d7q30n-002/svc:tesseract/2008,2543,220,80/full/0/default.jpg
```

is responding now

**Comment by DerekMaggio** [comment]
@jrmerz The unauthorized response bug was it. The whole time I thought ti was an authentication error... the image just didn't exist. Everything is now able to run locally without having to ping digital.ucdavis.edu. 

The problem is fixed. Thank you so much for your help. I appreciate it.
