### ISSUE TITLE
Contact Tesseract and Show Response at Bottom of Screen

### ISSUE THREAD

**Issue by DerekMaggio** [ucd-library/csus-sp-2018-app#6]

**Comment by DerekMaggio** [comment]
Provide @NimaSarraf with route of tesseract get call so he can make a button

**Comment by NimaSarraf** [comment]
@jrmerz So we're having trouble loading leaflet onto a polymer app. I'm importing our leaflet javascript file into the polymer element, and adding a div for it to be loaded in the html rendering of the element. The problem is, leaflet needs this div rendered before the javascript is rendered or else it throws an error because it can't find the div. Any ideas?

`import { PolymerElement, html } from '@polymer/polymer/polymer-element.js';
import './shared-styles.js';
import './leaflet/leaflet.js';



class MyView1 extends PolymerElement {
  static get template() {
    return html`
      <style include="shared-styles">
        :host {
          display: block;

          padding: 10px;
        }
      </style>

      <div class="card">
        <div class="circle">1</div>
        <h1>View One</h1>
        <div id="map" style="width: 900px; height: 500px"></div>

      </div>
    `;
  }
}

window.customElements.define('my-view1', MyView1);
`

**Comment by jrmerz** [comment]
Can you add your JavaScript code to the example?  It will allow me to specifically answer your question.  Here is some general help for this issue:

Element lifecycle:
https://www.polymer-project.org/3.0/docs/devguide/custom-elements#element-lifecycle

The UCD Dams image viewer uses leaflet, so you can use it for examples - 
leaflet imports (uses webpacks css loader):
https://github.com/UCDavisLibrary/fin-server/blob/master/services/ucd-lib-client/client/public/elements/pages/record/viewer/app-image-viewer-lightbox.js#L5

Map creation:
https://github.com/UCDavisLibrary/fin-server/blob/master/services/ucd-lib-client/client/public/elements/pages/record/viewer/app-image-viewer-lightbox.js#L162

Note, the flow above requires record data to be loaded as well as the image before the render method is called to create a map.  For your case, you can just use the 'ready' method, which is always called after the first time the element is attached to the document.  And make sure you add the leaflet styles to your elements ShadowDom (again done with webpack css loader, you could just add a link to the stylesheet directly inside your elements HTML as well): https://github.com/UCDavisLibrary/fin-server/blob/master/services/ucd-lib-client/client/public/elements/pages/record/viewer/app-image-viewer-lightbox.js#L17

**Comment by NimaSarraf** [comment]
So for the javascript in leaflet, it's particularly this line that's giving us trouble.

const map = L.map('map', { drawControl: true , crs: L.CRS.Simple});

When we're "adding the map", we get an error because we haven't made a div named "map" yet to be added, the div is in the polymer element's html so it gets rendered after our leaflet JS, so we're getting an error saying "Leaflet map container cannot be found".
I will go through the UCD Dams code today and see if I can try compare how we both implemented it.

**Comment by jrmerz** [comment]
Give a reference to the element instead of the elements id as a string.  So if you label the div 'map' inside your Polymer element, you can use Polymers $ id lookup to reference the element: 

```
const map = L.map(this.$.map, { drawControl: true , crs: L.CRS.Simple});
```

```document.querySelector``` will not search inside a ShadowDOM root and that's what older libraries (most likely) use to lookup element by id when a string is passed.   Passing DOM elements by Id string is becoming an anti pattern (IMHO) and I would suggest moving away from it, specially when using web components.

**Comment by jrmerz** [comment]
If you are really stuck, share the code with me (or point me to what I should be looking at) and tell me how to startup the app.  I can take a quick look to get you going again.

**Comment by NimaSarraf** [comment]
Actually I seem to have gotten it to work (For the most part)! Web Pack did the trick :)
The only thing that's not working is the leaflet CSS isn't loading in. I installed the webpack css loader and I'm not getting any "errors" in console, so I think it's the way I'm rendering it in shadowDOM.

This is the code in my polymer element:

```import leaflet from 'leaflet';
import leafletDraw from 'leaflet-draw';
import leafletCss from 'leaflet/dist/leaflet.css';


class MyApp extends PolymerElement {
  static get template() {
        let tag = document.createElement('template');
        tag.innerHTML = `<style>${leafletCss}</style>${template}`;
        return tag;
  }
```
And this is my webpack config file
```
module.exports = {
  entry: './src/my-app.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.(gif|png|jpe?g|svg)$/i,
        use: [
          'file-loader',
          {
            loader: 'image-webpack-loader',
            options: {
              bypassOnDebug: true, // webpack@1.x
              disable: true, // webpack@2.x and newer
            },
          },
        ],
      },
      {
        test: /\.css$/,
        use: [
          'file-loader',
          { loader: "style-loader" },
          { loader: "css-loader" }
        ]
      }
    ]
  }
}
```

I also tried to load the css directly into the index.html page with no luck. Do you have any ideas?

<img width="832" alt="screen shot 2018-10-24 at 10 43 02 am" src="https://user-images.githubusercontent.com/17836229/47450259-a1c72e00-d779-11e8-836b-87dcab9d517d.png">
